//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-619 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:03:04 PM CST 
//


package org.picketlink.idm.integration.jboss5.jaxb2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hibernateDeployerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hibernateDeployerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hibernateConfiguration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="hibernateSessionFactoryRegistryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="hibernateSessionFactoryJNDIName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hibernateDeployerType", propOrder = {
    "hibernateConfiguration",
    "hibernateSessionFactoryRegistryName",
    "hibernateSessionFactoryJNDIName"
})
public class HibernateDeployerType {

    @XmlElement(required = true)
    protected String hibernateConfiguration;
    protected String hibernateSessionFactoryRegistryName;
    protected String hibernateSessionFactoryJNDIName;

    /**
     * Gets the value of the hibernateConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHibernateConfiguration() {
        return hibernateConfiguration;
    }

    /**
     * Sets the value of the hibernateConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHibernateConfiguration(String value) {
        this.hibernateConfiguration = value;
    }

    /**
     * Gets the value of the hibernateSessionFactoryRegistryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHibernateSessionFactoryRegistryName() {
        return hibernateSessionFactoryRegistryName;
    }

    /**
     * Sets the value of the hibernateSessionFactoryRegistryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHibernateSessionFactoryRegistryName(String value) {
        this.hibernateSessionFactoryRegistryName = value;
    }

    /**
     * Gets the value of the hibernateSessionFactoryJNDIName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHibernateSessionFactoryJNDIName() {
        return hibernateSessionFactoryJNDIName;
    }

    /**
     * Sets the value of the hibernateSessionFactoryJNDIName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHibernateSessionFactoryJNDIName(String value) {
        this.hibernateSessionFactoryJNDIName = value;
    }

}
