//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-619 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:03:04 PM CST 
//


package org.picketlink.idm.integration.jboss5.jaxb2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hibernateInitializerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hibernateInitializerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="doChecking" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="setupLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hibernateInitializerType", propOrder = {
    "doChecking",
    "setupLocation"
})
public class HibernateInitializerType {

    protected boolean doChecking;
    @XmlElement(required = true)
    protected String setupLocation;

    /**
     * Gets the value of the doChecking property.
     * 
     */
    public boolean isDoChecking() {
        return doChecking;
    }

    /**
     * Sets the value of the doChecking property.
     * 
     */
    public void setDoChecking(boolean value) {
        this.doChecking = value;
    }

    /**
     * Gets the value of the setupLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetupLocation() {
        return setupLocation;
    }

    /**
     * Sets the value of the setupLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetupLocation(String value) {
        this.setupLocation = value;
    }

}
