//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-619 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:03:04 PM CST 
//


package org.picketlink.idm.integration.jboss5.jaxb2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for initializerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="initializerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="sqlInitializer" type="{urn:picketlink:idm:deployer:v1_0}sqlInitializerType"/>
 *           &lt;element name="hibernateInitializer" type="{urn:picketlink:idm:deployer:v1_0}hibernateInitializerType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "initializerType", propOrder = {
    "datasource",
    "sqlInitializer",
    "hibernateInitializer"
})
public class InitializerType {

    @XmlElement(required = true)
    protected String datasource;
    protected SqlInitializerType sqlInitializer;
    protected HibernateInitializerType hibernateInitializer;

    /**
     * Gets the value of the datasource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * Sets the value of the datasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasource(String value) {
        this.datasource = value;
    }

    /**
     * Gets the value of the sqlInitializer property.
     * 
     * @return
     *     possible object is
     *     {@link SqlInitializerType }
     *     
     */
    public SqlInitializerType getSqlInitializer() {
        return sqlInitializer;
    }

    /**
     * Sets the value of the sqlInitializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlInitializerType }
     *     
     */
    public void setSqlInitializer(SqlInitializerType value) {
        this.sqlInitializer = value;
    }

    /**
     * Gets the value of the hibernateInitializer property.
     * 
     * @return
     *     possible object is
     *     {@link HibernateInitializerType }
     *     
     */
    public HibernateInitializerType getHibernateInitializer() {
        return hibernateInitializer;
    }

    /**
     * Sets the value of the hibernateInitializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link HibernateInitializerType }
     *     
     */
    public void setHibernateInitializer(HibernateInitializerType value) {
        this.hibernateInitializer = value;
    }

}
