//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-619 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:03:04 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:picketlink:idm:deployer:v1_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.picketlink.idm.integration.jboss5.jaxb2;
