//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-619 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.19 at 09:03:04 PM CST 
//


package org.picketlink.idm.integration.jboss5.jaxb2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for picketlinkIDMDeployerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="picketlinkIDMDeployerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JNDIName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idmConfigFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hibernateDeployer" type="{urn:picketlink:idm:deployer:v1_0}hibernateDeployerType" minOccurs="0"/>
 *         &lt;element name="initializers" type="{urn:picketlink:idm:deployer:v1_0}initializerType" minOccurs="0"/>
 *         &lt;element name="options" type="{urn:picketlink:idm:deployer:v1_0}optionsType" minOccurs="0"/>
 *         &lt;element name="depends" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "picketlinkIDMDeployerType", propOrder = {
    "jndiName",
    "idmConfigFile",
    "hibernateDeployer",
    "initializers",
    "options",
    "depends"
})
public class PicketlinkIDMDeployerType {

    @XmlElement(name = "JNDIName", required = true)
    protected String jndiName;
    @XmlElement(required = true)
    protected String idmConfigFile;
    protected HibernateDeployerType hibernateDeployer;
    protected InitializerType initializers;
    protected OptionsType options;
    protected List<String> depends;

    /**
     * Gets the value of the jndiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJNDIName() {
        return jndiName;
    }

    /**
     * Sets the value of the jndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJNDIName(String value) {
        this.jndiName = value;
    }

    /**
     * Gets the value of the idmConfigFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdmConfigFile() {
        return idmConfigFile;
    }

    /**
     * Sets the value of the idmConfigFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdmConfigFile(String value) {
        this.idmConfigFile = value;
    }

    /**
     * Gets the value of the hibernateDeployer property.
     * 
     * @return
     *     possible object is
     *     {@link HibernateDeployerType }
     *     
     */
    public HibernateDeployerType getHibernateDeployer() {
        return hibernateDeployer;
    }

    /**
     * Sets the value of the hibernateDeployer property.
     * 
     * @param value
     *     allowed object is
     *     {@link HibernateDeployerType }
     *     
     */
    public void setHibernateDeployer(HibernateDeployerType value) {
        this.hibernateDeployer = value;
    }

    /**
     * Gets the value of the initializers property.
     * 
     * @return
     *     possible object is
     *     {@link InitializerType }
     *     
     */
    public InitializerType getInitializers() {
        return initializers;
    }

    /**
     * Sets the value of the initializers property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitializerType }
     *     
     */
    public void setInitializers(InitializerType value) {
        this.initializers = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link OptionsType }
     *     
     */
    public OptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionsType }
     *     
     */
    public void setOptions(OptionsType value) {
        this.options = value;
    }

    /**
     * Gets the value of the depends property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depends property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepends().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDepends() {
        if (depends == null) {
            depends = new ArrayList<String>();
        }
        return this.depends;
    }

}
